# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac420f202675ec6097dbcffd6fa09fce0c70fa29ac42ed90e506773c26008d9abbfe9ca7224df374c28f6a921ead8289575883e8e1f687411654c285afdf53e4

test:
  secret_key_base: e4ba0f2093e0b07924c19a5d37d31b031af4610a269ba51cb3068a753cd24ef1eb4a55f895e2e9012e1f0900e90270d6e2b2043fc542ff2d01dd9ff659b3d056

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
